const { snsClient, snsTopicArn } = require("../config/aws");

let PublishCommand, SubscribeCommand;
try {
  const snsPkg = require("@aws-sdk/client-sns");
  PublishCommand = snsPkg.PublishCommand;
  SubscribeCommand = snsPkg.SubscribeCommand;
} catch {
  // Graceful fallback when SDK is not present locally
}

const notificationService = {
  getStatus() {
    return {
      configured: Boolean(snsClient && snsTopicArn && PublishCommand),
      topicArn: snsTopicArn || "not-configured",
      mode: snsClient && snsTopicArn && PublishCommand ? "cloud-sns" : "local-simulation",
    };
  },

  async publishMessage(subject, message) {
    if (!snsClient || !snsTopicArn || !PublishCommand) {
      console.log(`[SNS Mock/Local] Alert Published -> Subject: "${subject}"\nMessage:\n${message}\n`);
      return { status: "simulated", subject };
    }

    try {
      const command = new PublishCommand({
        TopicArn: snsTopicArn,
        Subject: subject.slice(0, 100),
        Message: message,
      });
      const result = await snsClient.send(command);
      console.log(`[SNS Service] Successfully sent alert to SNS (MessageId: ${result.MessageId})`);
      return { status: "sent", messageId: result.MessageId };
    } catch (error) {
      console.error(`[SNS Service] Failed to send SNS alert: ${error.message}`);
      return { status: "error", error: error.message };
    }
  },

  async alertProductStatus(product) {
    const isExpired = product.status === "expired";
    const subject = isExpired
      ? `🚨 [SmartPantry] Expired Item Detected: ${product.name}`
      : `⚠️ [SmartPantry] Item Expiring Soon: ${product.name}`;

    const message = [
      `SmartPantry Inventory Alert`,
      `---------------------------------------`,
      `Product: ${product.name}`,
      `Quantity: ${product.quantity}`,
      `Expiry Date: ${product.expiry_date}`,
      `Current Status: ${product.status.toUpperCase()}`,
      `Timestamp: ${new Date().toISOString()}`,
      `---------------------------------------`,
      `Action Recommended: Please inspect your pantry and consume or dispose of this item promptly.`,
    ].join("\n");

    return this.publishMessage(subject, message);
  },

  async alertLowStock(product) {
    const subject = `🛒 [SmartPantry] Low Stock Warning: ${product.name}`;
    const message = [
      `SmartPantry Low Stock Warning`,
      `---------------------------------------`,
      `Product: ${product.name}`,
      `Remaining Quantity: ${product.quantity}`,
      `Expiry Date: ${product.expiry_date}`,
      `Timestamp: ${new Date().toISOString()}`,
      `---------------------------------------`,
      `Action Recommended: Restock this pantry essential soon.`,
    ].join("\n");

    return this.publishMessage(subject, message);
  },

  async alertAuditSweep(stats) {
    const subject = `📋 [SmartPantry] Pantry Audit Digest (${stats.total} total items)`;
    const message = [
      `SmartPantry Automated Audit Report`,
      `=======================================`,
      `Audit Execution Time: ${new Date().toISOString()}`,
      `Total Products Tracked: ${stats.total}`,
      `Fresh Items: ${stats.fresh}`,
      `Expiring Soon (<= 3 days): ${stats.soon}`,
      `Expired Items: ${stats.expired}`,
      `Low Stock Items: ${stats.lowStock}`,
      `=======================================`,
      `Summary of Actionable Items:`,
      ...stats.actionableItems.map(
        (i) => ` • [${i.status.toUpperCase()}] ${i.name} (Qty: ${i.quantity}, Expires: ${i.expiry_date})`
      ),
      `---------------------------------------`,
      `Generated by SmartPantry Cloud Inventory Management`,
    ].join("\n");

    return this.publishMessage(subject, message);
  },

  async subscribeEmail(email) {
    if (!email || !email.includes("@")) {
      throw new Error("Invalid email address provided");
    }

    if (!snsClient || !snsTopicArn || !SubscribeCommand) {
      console.log(`[SNS Mock/Local] Simulated email subscription for: ${email}`);
      return { status: "simulated", email };
    }

    try {
      const command = new SubscribeCommand({
        TopicArn: snsTopicArn,
        Protocol: "email",
        Endpoint: email.trim(),
      });
      const result = await snsClient.send(command);
      console.log(`[SNS Service] Subscribed email ${email} (SubscriptionArn: ${result.SubscriptionArn})`);
      return { status: "pending_confirmation", email, subscriptionArn: result.SubscriptionArn };
    } catch (error) {
      console.error(`[SNS Service] Failed to subscribe email: ${error.message}`);
      throw error;
    }
  },
};

module.exports = notificationService;
