version: '3.8'

services:

  mysql:

    image: mysql:8.4

    container_name: smartpantry-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartpantry
      MYSQL_USER: pantryuser
      MYSQL_PASSWORD: pantrypassword

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: